name: Terraform Kind CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Delete existing Kind cluster
        run: kind delete cluster || true

      - name: Create Kind Cluster (Free Tier Safe)
        run: kind create cluster --image kindest/node:v1.27.3 --wait 300s

      - name: Export kubeconfig
        run: echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Verify cluster
        run: kubectl get nodes

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Validate Pods
        run: kubectl get pods -A

      - name: Terraform Destroy
        if: always()
        working-directory: terraform
        run: terraform destroy -auto-approve

      - name: Delete Kind Cluster
        if: always()
        run: kind delete cluster || true
