name: Terraform Kind CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete existing Kind cluster (if any)
        run: kind delete cluster || true

      - name: Create Kind Cluster
        run: kind create cluster --wait 300s

      - name: Set KUBECONFIG
        run: echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Verify cluster
        run: kubectl cluster-info && kubectl get nodes

      - name: Give Kubernetes time to stabilize
        run: sleep 60

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Validate Pods
        run: kubectl get pods -A

      - name: Terraform Destroy
        if: always()
        working-directory: terraform
        run: |
          terraform init
          terraform destroy -auto-approve

      - name: Delete Kind Cluster
        if: always()
        run: kind delete cluster || true
